CREATE TABLE IF NOT EXISTS cities (
  id        TEXT    PRIMARY KEY,   -- slug: e.g. 'mumbai', 'delhi'
  name      TEXT    NOT NULL,
  state     TEXT    NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- Seed: all 61 cities supported by the Gemini AI rate scheduler
-- ApiConstants.kt CITIES list must match these IDs exactly.
INSERT INTO cities (id, name, state) VALUES
  ('mumbai', 'Mumbai', 'Maharashtra'),
  ('delhi', 'Delhi', 'Delhi'),
  ('kolkata', 'Kolkata', 'West Bengal'),
  ('chennai', 'Chennai', 'Tamil Nadu'),
  ('bangalore', 'Bangalore', 'Karnataka'),
  ('hyderabad', 'Hyderabad', 'Telangana'),
  ('pune', 'Pune', 'Maharashtra'),
  ('ahmedabad', 'Ahmedabad', 'Gujarat'),
  ('jaipur', 'Jaipur', 'Rajasthan'),
  ('surat', 'Surat', 'Gujarat'),
  ('lucknow', 'Lucknow', 'Uttar Pradesh'),
  ('kanpur', 'Kanpur', 'Uttar Pradesh'),
  ('nagpur', 'Nagpur', 'Maharashtra'),
  ('indore', 'Indore', 'Madhya Pradesh'),
  ('bhopal', 'Bhopal', 'Madhya Pradesh'),
  ('visakhapatnam', 'Visakhapatnam', 'Andhra Pradesh'),
  ('patna', 'Patna', 'Bihar'),
  ('vadodara', 'Vadodara', 'Gujarat'),
  ('ghaziabad', 'Ghaziabad', 'Uttar Pradesh'),
  ('agra', 'Agra', 'Uttar Pradesh'),
  ('meerut', 'Meerut', 'Uttar Pradesh'),
  ('nashik', 'Nashik', 'Maharashtra'),
  ('faridabad', 'Faridabad', 'Haryana'),
  ('rajkot', 'Rajkot', 'Gujarat'),
  ('varanasi', 'Varanasi', 'Uttar Pradesh'),
  ('srinagar', 'Srinagar', 'Jammu & Kashmir'),
  ('aurangabad', 'Aurangabad', 'Maharashtra'),
  ('coimbatore', 'Coimbatore', 'Tamil Nadu'),
  ('madurai', 'Madurai', 'Tamil Nadu'),
  ('thiruvananthapuram', 'Thiruvananthapuram', 'Kerala'),
  ('ranchi', 'Ranchi', 'Jharkhand'),
  ('jabalpur', 'Jabalpur', 'Madhya Pradesh'),
  ('gwalior', 'Gwalior', 'Madhya Pradesh'),
  ('vijayawada', 'Vijayawada', 'Andhra Pradesh'),
  ('jodhpur', 'Jodhpur', 'Rajasthan'),
  ('raipur', 'Raipur', 'Chhattisgarh'),
  ('kota', 'Kota', 'Rajasthan'),
  ('guwahati', 'Guwahati', 'Assam'),
  ('bhubaneswar', 'Bhubaneswar', 'Odisha'),
  ('tiruchirappalli', 'Tiruchirappalli', 'Tamil Nadu'),
  ('noida', 'Noida', 'Uttar Pradesh'),
  ('gurgaon', 'Gurgaon', 'Haryana'),
  ('bikaner', 'Bikaner', 'Rajasthan'),
  ('dehradun', 'Dehradun', 'Uttarakhand'),
  ('prayagraj', 'Prayagraj', 'Uttar Pradesh'),
  ('mangalore', 'Mangalore', 'Karnataka'),
  ('mysore', 'Mysore', 'Karnataka'),
  ('hubli', 'Hubli', 'Karnataka'),
  ('belgaum', 'Belgaum', 'Karnataka'),
  ('jalandhar', 'Jalandhar', 'Punjab'),
  ('ludhiana', 'Ludhiana', 'Punjab'),
  ('amritsar', 'Amritsar', 'Punjab'),
  ('chandigarh', 'Chandigarh', 'Punjab'),
  ('siliguri', 'Siliguri', 'West Bengal'),
  ('udaipur', 'Udaipur', 'Rajasthan'),
  ('ajmer', 'Ajmer', 'Rajasthan'),
  ('bhilai', 'Bhilai', 'Chhattisgarh'),
  ('jammu', 'Jammu', 'Jammu & Kashmir'),
  ('shimla', 'Shimla', 'Himachal Pradesh'),
  ('shillong', 'Shillong', 'Meghalaya'),
  ('imphal', 'Imphal', 'Manipur')
ON CONFLICT (id) DO NOTHING;
